POST http://localhost:8081/authorization/register?username=admin&password=admin
Authorization: Basic kgtjwtclientid MtivuBUrFYEHd
Content-Type: application/x-www-form-urlencoded

###

POST http://localhost:8081/oauth/token?grant_type=password&username=admin&password=admin
Authorization: Basic kgtjwtclientid MtivuBUrFYEHd
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8761/authorization/authorization/user-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2d0and0cmVzb3VyY2VpZCJdLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZGV0YWlscyI6eyJpZCI6IjQwMjhiODgxN2VlNjI2YzcwMTdlZTYyNzAwNzAwMDAwIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOSVNUUkFUT1IiXX0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJleHAiOjE2NDQ1Njc2NDAsImF1dGhvcml0aWVzIjpbIkFETUlOSVNUUkFUT1IiXSwianRpIjoiOTQxOWMwYzItYmExOC00NDgzLWE4OTQtM2I1MmFmNGMyYTQzIiwiY2xpZW50X2lkIjoia2d0and0Y2xpZW50aWQifQ.Spu28UbYkqC7FdOXk2Lgc5-_X6agqqOiLRh1Xv_Nd9g

###
GET http://localhost:8761/registry/ui
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsia2d0and0cmVzb3VyY2VpZCJdLCJ1c2VyX25hbWUiOiJhZG1pbiIsInVzZXJfZGV0YWlscyI6eyJpZCI6IjQwMjhiODgxN2VlNjI2YzcwMTdlZTYyNzAwNzAwMDAwIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbIkFETUlOSVNUUkFUT1IiXX0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJleHAiOjE2NDQ1Njc2NDAsImF1dGhvcml0aWVzIjpbIkFETUlOSVNUUkFUT1IiXSwianRpIjoiOTQxOWMwYzItYmExOC00NDgzLWE4OTQtM2I1MmFmNGMyYTQzIiwiY2xpZW50X2lkIjoia2d0and0Y2xpZW50aWQifQ.Spu28UbYkqC7FdOXk2Lgc5-_X6agqqOiLRh1Xv_Nd9g
